'use client';

import { ArrowDownRight, Check, ChevronRight, Clipboard, Code2, ExternalLink, Filter, Search, ShieldCheck, Terminal, Zap } from 'lucide-react';
import { useMemo, useState } from 'react';

type Pattern = { name: string; category: 'สรุปและวิเคราะห์' | 'คอนเทนต์' | 'กลยุทธ์ธุรกิจ' | 'งานประจำวัน'; thai: string; description: string; input: string };
const patterns: Pattern[] = [
  { name: 'summarize', category: 'สรุปและวิเคราะห์', thai: 'สรุปให้กระชับ', description: 'เปลี่ยนบทความ รายงาน หรือโน้ตยาวให้เป็นสาระสำคัญที่อ่านจบไว', input: 'วางบทความ / ส่ง URL ที่ต้องการสรุป' },
  { name: 'extract_wisdom', category: 'สรุปและวิเคราะห์', thai: 'ดึงบทเรียนที่นำไปใช้ได้', description: 'ค้นหาแนวคิดและข้อคิดที่มีคุณค่าจากบทความ พอดแคสต์ หรือบทสนทนา', input: 'วาง transcript หรือบทความฉบับเต็ม' },
  { name: 'extract_insights', category: 'สรุปและวิเคราะห์', thai: 'แยกอินไซต์สำคัญ', description: 'แปลงข้อมูลดิบเป็นประเด็นเชิงลึกที่ช่วยตัดสินใจหรือต่อยอดงาน', input: 'รายงาน ลูกค้ารีวิว หรือบันทึกประชุม' },
  { name: 'extract_main_idea', category: 'สรุปและวิเคราะห์', thai: 'หาใจความหลัก', description: 'ตอบให้ชัดว่าเนื้อหานี้ยืนยันหรือสื่อสารเรื่องอะไรเป็นหลัก', input: 'ข้อความยาวที่ต้องการจับประเด็น' },
  { name: 'analyze_claims', category: 'สรุปและวิเคราะห์', thai: 'วิเคราะห์ข้ออ้าง', description: 'แยกข้ออ้าง เหตุผล และจุดที่ควรตรวจสอบเพิ่มเติมก่อนเชื่อหรือแชร์', input: 'โพสต์ ข่าว หรือข้อเสนอที่ต้องการตรวจตรา' },
  { name: 'rate_content', category: 'สรุปและวิเคราะห์', thai: 'ประเมินความคุ้มค่าในการอ่าน', description: 'ช่วยตัดสินใจว่าเนื้อหาชิ้นนี้มีคุณภาพและควรใช้เวลาต่อหรือไม่', input: 'ลิงก์หรือข้อความเนื้อหาที่สนใจ' },
  { name: 'create_summary', category: 'สรุปและวิเคราะห์', thai: 'สร้างสรุปแบบมีโครงสร้าง', description: 'เรียบเรียงสรุปเป็นหัวข้อเพื่อส่งต่อทีม หรือใช้เป็นโน้ตอ้างอิง', input: 'บทความ รายงาน หรือบันทึกงาน' },
  { name: 'create_social_media_post', category: 'คอนเทนต์', thai: 'ร่างโพสต์โซเชียล', description: 'นำเนื้อหาต้นฉบับมาแตกเป็นโพสต์ที่สื่อสารง่ายและน่าสนใจ', input: 'บทความ ลิงก์ หรือประเด็นที่อยากเล่า' },
  { name: 'write_essay', category: 'คอนเทนต์', thai: 'เขียนบทความจากไอเดีย', description: 'ต่อยอดแนวคิดสั้น ๆ ให้เป็นร่างบทความที่มีลำดับและน้ำเสียงชัดเจน', input: 'หัวข้อ ไอเดีย หรือโครงร่างคร่าว ๆ' },
  { name: 'improve_writing', category: 'คอนเทนต์', thai: 'ปรับงานเขียน', description: 'ทำให้ภาษาอ่านลื่น กระชับ และสื่อความหมายตรงขึ้นโดยคงสารเดิม', input: 'ร่างอีเมล บทความ หรือข้อความขาย' },
  { name: 'create_newsletter_entry', category: 'คอนเทนต์', thai: 'ร่างเนื้อหา Newsletter', description: 'แปลงเรื่องที่น่าสนใจให้เป็นช่วงเนื้อหาสำหรับจดหมายข่าว', input: 'ลิงก์ บทความ หรือหัวข้อประจำสัปดาห์' },
  { name: 'create_micro_summary', category: 'คอนเทนต์', thai: 'สรุปสั้นมาก', description: 'ย่อสาระให้พร้อมใช้เป็น caption, executive note หรือข้อความเปิดเรื่อง', input: 'เนื้อหาต้นฉบับหนึ่งชิ้น' },
  { name: 'create_marketing_strategy', category: 'กลยุทธ์ธุรกิจ', thai: 'วางกลยุทธ์การตลาด', description: 'ช่วยแตกโจทย์สินค้า กลุ่มเป้าหมาย และแนวทางสื่อสารเป็นแผนเริ่มต้น', input: 'รายละเอียดสินค้า ลูกค้า และเป้าหมาย' },
  { name: 'extract_business_ideas', category: 'กลยุทธ์ธุรกิจ', thai: 'ค้นหาไอเดียธุรกิจ', description: 'มองหาโอกาส ปัญหาลูกค้า และแนวคิดต่อยอดจากเนื้อหาที่มีอยู่', input: 'บทความ เทรนด์ หรือบันทึกไอเดีย' },
  { name: 'extract_recommendations', category: 'กลยุทธ์ธุรกิจ', thai: 'ดึงข้อเสนอแนะ', description: 'รวบรวม action items ที่ถูกเสนอไว้ในเอกสารให้เป็นรายการลงมือทำ', input: 'รายงานประชุม ผลวิจัย หรือเอกสารวิเคราะห์' },
  { name: 'create_prd', category: 'กลยุทธ์ธุรกิจ', thai: 'ร่างเอกสารผลิตภัณฑ์', description: 'เปลี่ยนไอเดียฟีเจอร์เป็น Product Requirements Document ฉบับตั้งต้น', input: 'ปัญหา ผู้ใช้เป้าหมาย และผลลัพธ์ที่ต้องการ' },
  { name: 'clean_text', category: 'งานประจำวัน', thai: 'จัดข้อความให้สะอาด', description: 'ล้างข้อความที่คัดลอกจาก PDF, เว็บ หรือ transcript ให้พร้อมใช้งานต่อ', input: 'ข้อความที่มีบรรทัดเกินหรือรูปแบบเพี้ยน' },
  { name: 'extract_questions', category: 'งานประจำวัน', thai: 'ดึงคำถามที่ค้างอยู่', description: 'หาคำถาม ประเด็นที่ยังไม่ชัด และสิ่งที่ทีมต้องตอบจากเอกสาร', input: 'บันทึกประชุมหรือเอกสารโครงการ' },
];
const categories = ['ทั้งหมด', ...new Set(patterns.map((pattern) => pattern.category))];

function CopyButton({ value, label = 'คัดลอกคำสั่ง' }: { value: string; label?: string }) {
  const [copied, setCopied] = useState(false);
  const copy = async () => { await navigator.clipboard.writeText(value); setCopied(true); window.setTimeout(() => setCopied(false), 1800); };
  return <button onClick={copy} className="copy-button" aria-label={label}>{copied ? <Check size={15} /> : <Clipboard size={15} />}{copied ? 'คัดลอกแล้ว' : label}</button>;
}

export default function Home() {
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState('ทั้งหมด');
  const [visibleCount, setVisibleCount] = useState(9);
  const filteredPatterns = useMemo(() => patterns.filter((pattern) => {
    const haystack = `${pattern.name} ${pattern.thai} ${pattern.description} ${pattern.category}`.toLowerCase();
    return (category === 'ทั้งหมด' || pattern.category === category) && haystack.includes(query.toLowerCase());
  }), [category, query]);
  return <main>
    <header className="site-header"><a className="brand" href="#top" aria-label="Fabric Thai Guide"><span className="brand-mark"><Terminal size={20} /></span><span>FABRIC <i>THAI GUIDE</i></span></a><nav aria-label="เมนูหลัก"><a href="#start">เริ่มต้นใช้</a><a href="#workflow">ขั้นตอนทำงาน</a><a href="#patterns">คลัง Patterns</a></nav><a className="github-link" href="https://github.com/danielmiessler/Fabric" target="_blank" rel="noreferrer"><Code2 size={17} /> GitHub</a></header>
    <section id="top" className="hero section-shell"><div className="hero-copy"><p className="eyebrow"><Zap size={15} /> AI WORKFLOW, WITHOUT THE NOISE</p><h1>เปลี่ยน AI ให้เป็น<br /><em>ผู้ช่วยที่ใช้งานได้จริง</em></h1><p className="hero-lede">Fabric คือเครื่องมือ command line ที่รวม <strong>Patterns</strong> หรือพรอมป์ต์ตามงานจริงไว้ให้คุณเรียกใช้ซ้ำได้อย่างเป็นระบบ</p><div className="hero-actions"><a className="primary-button" href="#start">เริ่มใน 3 ขั้นตอน <ArrowDownRight size={18} /></a><a className="text-button" href="#patterns">เลือก Pattern ให้เหมาะกับงาน <ChevronRight size={17} /></a></div></div><div className="terminal-window" aria-label="ตัวอย่างการใช้ Fabric"><div className="terminal-top"><span /><span /><span /><b>PowerShell</b></div><div className="terminal-body"><p><span className="terminal-prompt">PS&gt;</span> fabric --pattern summarize</p><p className="terminal-muted">วางบทความหรือ URL แล้วกด Enter</p><div className="terminal-result"><span>✓</span><div><b>สรุปเรียบร้อย</b><br />ได้ประเด็นสำคัญและสิ่งที่ทำต่อได้</div></div></div><div className="pattern-chip">Pattern: <b>summarize</b></div></div></section>
    <section className="trust-strip section-shell"><div><b>Fabric ไม่ใช่แชตบอต</b><span>เป็นเครื่องมือจัดระเบียบและเรียกใช้พรอมป์ต์</span></div><div><b>คุณควบคุมข้อมูลเอง</b><span>ตั้งค่า AI provider ของคุณในเครื่อง</span></div><div><b>ทำงานซ้ำได้เร็ว</b><span>Pattern เดิม ใช้กับข้อมูลใหม่ได้ทุกวัน</span></div></section>
    <section id="start" className="guide-section section-shell"><div className="section-heading"><p className="eyebrow">QUICK START / WINDOWS</p><h2>เริ่มใช้งานใน 3 ขั้นตอน</h2><p>ไม่ต้องเขียนโค้ด และหน้านี้จะไม่ขอหรือเก็บ API key ของคุณ</p></div><div className="steps-grid">{[['01', 'ติดตั้ง Fabric', 'เปิด PowerShell แล้วติดตั้งผ่าน Windows Package Manager', 'winget install danielmiessler.Fabric'], ['02', 'เชื่อมต่อ AI ที่คุณใช้', 'ตั้งค่า provider และ API key ใน Fabric บนเครื่องของคุณเท่านั้น', 'fabric --setup'], ['03', 'ลองคำสั่งแรก', 'ใส่ข้อความหรือ URL แล้วให้ Pattern ช่วยสรุปเนื้อหา', 'fabric --pattern summarize']].map(([number, title, description, command]) => <article className="step-card" key={number}><span className="step-number">{number}</span><h3>{title}</h3><p>{description}</p><div className="command"><code>{command}</code><CopyButton value={command} label="คัดลอก" /></div></article>)}</div><aside className="security-note"><ShieldCheck size={20} /><p><b>เรื่อง API key:</b> เก็บไว้ในการตั้งค่า Fabric บนคอมพิวเตอร์ของคุณ ไม่ต้องวาง key ลงในเว็บหน้านี้ และอย่าส่ง key ให้ผู้อื่น</p></aside></section>
    <section id="workflow" className="workflow-section"><div className="section-shell workflow-inner"><div className="section-heading"><p className="eyebrow">A REPEATABLE WORKFLOW</p><h2>จากข้อมูลยาว ๆ สู่คำตอบที่นำไปทำงานต่อได้</h2></div><div className="workflow-grid">{[['01', 'เตรียมข้อมูล', 'วางข้อความ, URL, transcript หรือโน้ตที่คุณมี'], ['02', 'เลือก Pattern', 'เลือกงานที่อยากได้ เช่น สรุป วิเคราะห์ หรือร่างคอนเทนต์'], ['03', 'รันใน Terminal', 'คัดลอกคำสั่งจากหน้านี้ แล้ววางใน PowerShell'], ['04', 'ตรวจและต่อยอด', 'ตรวจความถูกต้อง ปรับมุมมอง แล้วใช้ผลลัพธ์เป็นร่างแรก']].map(([number, title, description]) => <article className="workflow-item" key={number}><span>{number}</span><div><h3>{title}</h3><p>{description}</p></div></article>)}</div></div></section>
    <section id="patterns" className="patterns-section section-shell"><div className="section-heading split-heading"><div><p className="eyebrow">PATTERN LIBRARY</p><h2>เลือกคำสั่งที่ตรงกับงานคุณ</h2><p>ชื่อ Pattern เป็นภาษาอังกฤษตาม Fabric ส่วนคำอธิบายและวิธีใช้แปลเป็นไทยเพื่อให้เริ่มได้ทันที</p></div><span className="count-badge">{patterns.length} PATTERNS</span></div><div className="pattern-controls"><label className="search-box"><Search size={19} /><input value={query} onChange={(event) => { setQuery(event.target.value); setVisibleCount(9); }} placeholder="ค้นหา เช่น สรุป, การตลาด, social media" /></label><div className="filter-row" aria-label="กรองหมวดงาน"><Filter size={17} />{categories.map((item) => <button key={item} onClick={() => { setCategory(item); setVisibleCount(9); }} className={category === item ? 'active' : ''}>{item}</button>)}</div></div><div className="pattern-grid">{filteredPatterns.slice(0, visibleCount).map((pattern) => { const command = `fabric --pattern ${pattern.name}`; return <article className="pattern-card" key={pattern.name}><div className="card-top"><span className="category-tag">{pattern.category}</span><a href={`https://github.com/danielmiessler/Fabric/tree/main/data/patterns/${pattern.name}`} target="_blank" rel="noreferrer" aria-label={`ดู Pattern ${pattern.name} บน GitHub`}><ExternalLink size={16} /></a></div><h3>{pattern.thai}</h3><code className="pattern-name">{pattern.name}</code><p>{pattern.description}</p><div className="input-hint"><b>ลองใช้กับ</b><span>{pattern.input}</span></div><div className="command pattern-command"><code>{command}</code><CopyButton value={command} /></div></article>; })}</div>{filteredPatterns.length === 0 && <div className="empty-state">ไม่พบ Pattern ที่ตรงกับคำค้น ลองใช้คำสั้นลง หรือเลือก “ทั้งหมด”</div>}{visibleCount < filteredPatterns.length && <div className="more-wrap"><button className="more-button" onClick={() => setVisibleCount((count) => count + 9)}>แสดง Patterns เพิ่มเติม <ChevronRight size={17} /></button></div>}</section>
    <section className="source-callout section-shell"><div><p className="eyebrow">KEEP EXPLORING</p><h2>ต้องการดู prompt ต้นฉบับเต็ม?</h2><p>Patterns มีการพัฒนาอยู่เสมอ จึงควรดูเวอร์ชันล่าสุดจาก Fabric โดยตรงก่อนปรับใช้กับงานสำคัญ</p></div><a className="primary-button" href="https://github.com/danielmiessler/Fabric/tree/main/data/patterns" target="_blank" rel="noreferrer">เปิดคลัง Patterns <ExternalLink size={17} /></a></section>
    <footer><span>FABRIC THAI GUIDE</span><p>คู่มือใช้งานเบื้องต้น ไม่ใช่เว็บไซต์ทางการของ Fabric</p><a href="https://github.com/danielmiessler/Fabric" target="_blank" rel="noreferrer">GitHub ของ Fabric <ExternalLink size={13} /></a></footer>
  </main>;
}
